#! /bin/sh

if test $# -ne 2
then
	echo Usage: $0 IFACE IP/MASK
	exit 1
fi

ovs-vsctl add-br gateway
ovs-vsctl set-controller gateway tcp:127.0.0.1
ip link set gateway up

ip addr del $2 dev $1
ip addr add $2 dev gateway
ovs-vsctl add-port gateway $1
