#! /bin/sh

ovs-vsctl add-br triangle
ovs-vsctl set-controller triangle tcp:127.0.0.1
ip link set triangle up

ip addr del 192.168.56.3/24 dev eth1
ip addr add 192.168.56.3/24 dev triangle
ovs-vsctl add-port triangle eth1

ip netns add application
ip link add application type veth \
	peer name eth0 address 00:00:00:00:00:02 netns application
ip link set application up
ip addr add 10.0.0.1/24 dev triangle
ovs-vsctl add-port triangle application

ip netns exec application sh <<END
ip link set lo up
ip link set eth0 up
ip addr add 10.0.0.2/24 dev eth0
ip route add default via 10.0.0.1
END
