#! /bin/sh

ovs-vsctl add-br gateway
ovs-vsctl set-controller gateway tcp:127.0.0.1
ip link set gateway up

ip addr del 192.168.56.1/24 dev eth0
ip addr add 192.168.56.1/24 dev gateway
ovs-vsctl add-port gateway eth0
